language: node_js
node_js:
  - "8"
install:
  - yarn
  - yarn global add now
script:
  - yarn build
  - yarn test
  - yarn ci:now:deploy
  - sleep 10
  - yarn ci:now:alias
  - sleep 10
  - yarn ci:now:clean
